In [10]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [2]:

import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

Decision Tree




In [37]:
data1 = pd.read_csv("train.csv", nrows=2000, usecols=[22,13,17,16,15,14])
data1.head()

srch_adults_cnt  srch_children_cnt  srch_rm_cnt  srch_destination_id  \
0                2                  0            1                 8250   
1                2                  0            1                 8250   
2                2                  0            1                 8250   
3                2                  0            1                14984   
4                2                  0            1                14984   

   srch_destination_type_id  hotel_market  
0                         1           628  
1                         1           628  
2                         1           628  
3                         1          1457  
4                         1          1457

In [31]:
data2 = pd.read_csv("test.csv", nrows=2000,  usecols=[21,18,17,16,15,14])
data2.head()

srch_adults_cnt  srch_children_cnt  srch_rm_cnt  srch_destination_id  \
0                2                  0            1                12243   
1                2                  0            1                14474   
2                4                  0            1                11353   
3                2                  0            1                 8250   
4                2                  0            1                11812   

   srch_destination_type_id  hotel_market  
0                         6            27  
1                         7          1540  
2                         1           699  
3                         1           628  
4                         1           538

In [38]:
X_train, X_test, y_train, y_test = train_test_split( data1, data2, test_size = 0.3, random_state = 100)

In [39]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=3, min_samples_leaf=5)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=100, splitter='best')

In [40]:
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=100, splitter='best')

In [41]:
clf_gini.predict([[4, 4, 3, 3,4,4]])

array([[   2,    0,    1, 8250,    1,  628]], dtype=int64)

In [42]:
y_pred = clf_gini.predict(X_test)
y_pred

array([[   2,    0,    1, 8250,    1,  628],
       [   2,    0,    1, 8250,    1,  628],
       [   2,    0,    1, 8250,    1,  365],
       ...,
       [   2,    0,    1, 8250,    1,  628],
       [   2,    0,    1, 8267,    1,  675],
       [   2,    0,    1, 8250,    1,  628]], dtype=int64)

accurecy is low

KNN

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
neigh = KNeighborsClassifier(n_neighbors=3)

In [45]:
neigh.fit(data1, data2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [46]:
print(neigh.predict(y_test))

[[    2     0     1 21311     6    91]
 [    2     0     1  8242     1    61]
 [    1     0     1   112     1    27]
 ...
 [    2     0     1  8241     1    32]
 [    1     0     1  8739     1     4]
 [    2     0     1  8273     1   660]]


In [50]:
neigh.score( y_train,X_train,sample_weight=None)


ValueError: multiclass-multioutput is not supported

In [47]:
score(self, X, y, sample_weight=None)

NameError: name 'score' is not defined

1

logistical regreassion

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
from sklearn.datasets import load_iris

In [56]:
X, y = load_iris(return_X_y=True)
clf = LogisticRegression(random_state=0, solver='lbfgs',
                         multi_class='multinomial').fit(X, y)
clf.predict(X[:2, :])

clf.predict_proba(X[:2, :]) 

clf.score(X, y)


C:\Users\Spencer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.9733333333333334

In [57]:
X.head()
y.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'